# Generated by Django 4.2.5 on 2023-09-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotcategories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='Appartements',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='Cars',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='FoodAndLife',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='Shopping',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='Travelling',
            field=models.CharField(default='', max_length=30),
        ),
    ]
