# Generated by Django 4.2.5 on 2023-09-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('car', models.BooleanField(default=False)),
                ('appartements', models.BooleanField(default=False)),
                ('shopping', models.BooleanField(default=False)),
                ('travelling', models.BooleanField(default=False)),
                ('foodandlife', models.BooleanField(default=False)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('title', models.CharField(default='', max_length=100)),
                ('listing_type', models.CharField(choices=[('car', 'car'), ('appartements', 'appartements'), ('shopping', 'shopping'), ('travelling', 'travelling'), ('foodandlife', 'foodandlife')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_password', models.CharField(max_length=100)),
                ('new_password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
            ],
        ),
    ]
