# Generated by Django 4.2.5 on 2023-09-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetPassword',
        ),
    ]
