# Generated by Django 4.2.5 on 2023-09-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotapp', '0002_delete_resetpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='Contact',
        ),
    ]
